#!/usr/bin/env python
import platform
import Options

obj = bld(
	features  = 'cc cprogram',
	uselib    = 'GLIB LIBXML2 SDL GTK',
	target    = 'otternduck',
	includes  = '.. .',
	linkflags = ['-g'],
	ccflags   = ['-g']
)
if bld.env['LMINGW'] == 'mingw32':
	obj.libs = ['SDL_image','mingw32','SDLmain']
else:
	obj.libs = ['SDL_image']
obj.find_sources_in_dirs('.')
